language: objective-c
osx_image: xcode7.3
sudo: false
language: ruby
#cache: bundler
rvm:
- 2.2.3
env:
  global:
    - PATH=$HOME/.local/bin:$PATH
    - NO_HEADLESS=yes
before_install:
# broken phantom
#- phantomjs -v
#- npm update
#- npm install phantomjs
#- phantomjs -v
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
- openssl aes-256-cbc -K $encrypted_d99751a86d14_key -iv $encrypted_d99751a86d14_iv -in etc/deploy.enc -out $HOME/deploy -d
- chmod 600 $HOME/deploy
- pip install --user linkchecker
- git config --global user.email "wojciech@koszek.com"
- git config --global user.name "Wojciech A. Koszek"
- git remote add github git@github.com:wkoszek/me.git
script:
- cp etc/ssh_config ~/.ssh/config
- make bootstrap doit pub
addons:
  apt:
    packages:
    - aspell
    - aspell-en
    - nginx
    - linkchecker
    - libgmp-dev
    - nodejs
