sudo: false
language: ruby
rvm:
- 2.2.3
env:
  global:
    - PATH=$HOME/.local/bin:$PATH
before_install:
- openssl aes-256-cbc -K $encrypted_d99751a86d14_key -iv $encrypted_d99751a86d14_iv -in etc/deploy.enc -out $HOME/deploy -d
- pip install --user linkchecker
- git config --global user.email "wojciech@koszek.com"
- git config --global user.name "Wojciech A. Koszek"
script:
- cp etc/ssh_config ~/.ssh/config
- make bootstrap doit pub
addons:
  apt:
    packages:
    - aspell
    - aspell-en
    - nginx
    - linkchecker
    - libgmp-dev
    - nodejs
