sudo: required
group: edge
language: ruby
services:
  - docker

before_install:
- openssl aes-256-cbc -K $encrypted_d99751a86d14_key -iv $encrypted_d99751a86d14_iv -in etc/deploy.enc -out etc/deploy -d
- chmod 600 etc/deploy
- git config --global user.email "wojciech@koszek.com"
- git config --global user.name "Wojciech A. Koszek"
- git remote add github git@github.com:wkoszek/me.git
script:
- docker pull wkoszek/me
- docker run -ti -v .:/me -w /me wkoszek/me
#- cp etc/ssh_config ~/.ssh/config
#- make bootstrap doit pub
