language: ruby
rvm:
- 2.2.3
script:
- make bootstrap
- make doit
before_install:
- sudo pip install linkchecker
addons:
  apt:
    packages:
    - aspell
    - aspell-en
    - nginx
    - linkchecker
