sudo: false
language: ruby
rvm:
- 2.2.3
env:
  global:
    - PATH=$HOME/.local/bin:$PATH
before_install:
- cd etc && openssl aes-256-cbc -K $encrypted_d99751a86d14_key -iv $encrypted_d99751a86d14_iv -in deploy.enc -out $HOME/deploy -d
- pip install --user linkchecker
script:
- pwd
- cp etc/ssh_config ~/.ssh/config
- make bootstrap doit pub
addons:
  apt:
    packages:
    - aspell
    - aspell-en
    - nginx
    - linkchecker
